server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://106.15.238.125:8010/eureka/

  instance:
    prefer-ip-address: true
    instance-id: kele-practise
    health-check-url-path: /actuator/health

spring:
  application:
    name: kele-practise

  #数据源相关配置;
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/keledb
    username: xukele
    password: kele123
  
    druid:
      initial-size: 10
      min-idle: 3
      max-active: 40
      max-wait: 10000
      test-on-borrow: false
      test-on-return: false
  #      web-stat-filter:
  #        enabled: true
  #      filter:
  #        stat:
  #          slow-sql-millis: 6000
  #          log-slow-sql: true
  #      stat-view-servlet:
  #        enabled: true
  #        login-username: kele
  #        login-password: kele123

  #spring-data-jpa-config
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #redis缓存 默认实现是 lettuceConnection;
  redis:
    host: 106.15.238.125
    password: $2a$10$i/PCl4EKKPcKYfsHi/aKA.AT/9QVWQI.vWBdBO/rLsB7PuFXu30ti
    port: 6379
  #定时任务配置
  quartz:
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      #获取锁后执行任务,防止并发情况下污染数据;
      acquireTriggersWithinLock: true

#actuator监控接口配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: /usr/local/logfiles/practise.log