server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://192.168.226.100:9010/eureka/

  instance:
    prefer-ip-address: true
    instance-id: kele-practise
    health-check-url-path: /actuator/health

spring:
  application:
    name: kele-practise

  #数据源相关配置;
  datasource:
    url: jdbc:mysql://192.168.226.100:3306/keledb?useUnicode=true&characterEncoding=utf8
    username: root
    password: Jialele666%

  #spring-data-jpa-config
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  #redis缓存 默认实现是 lettuceConnection;
  redis:
    host: 192.168.226.100
    password: $2a$10$qy7Bt9VFjZFZ06SyToG9XehXJ8YJDo1r4tDQ9DSYvfV9Pye5ibwLW
    port: 6379
  #定时任务配置
  quartz:
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      #获取锁后执行任务,防止并发情况下污染数据;
      acquireTriggersWithinLock: true

#actuator监控接口配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: /usr/local/logfiles/practise.log